# Generated by Django 5.1.1 on 2024-09-06 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="genre",
            field=models.CharField(
                choices=[
                    ("Fiction", "Fiction"),
                    ("Non-fiction", "Non-fiction"),
                    ("Science Fiction", "Science Fiction"),
                    ("Fantasy", "Fantasy"),
                    ("Biography", "Biography"),
                    ("Mystery", "Mystery"),
                    ("Romance", "Romance"),
                    ("Horror", "Horror"),
                ],
                default="Fiction",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="book",
            name="origin",
            field=models.CharField(
                choices=[("Original", "Original"), ("Gifted", "Gifted")],
                default="Original",
                max_length=8,
            ),
        ),
    ]
