# Generated by Django 5.1.1 on 2024-09-07 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_book_genre_alter_book_origin"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookrating",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="book_ratings",
                to="users.profile",
            ),
        ),
    ]
