# Generated by Django 5.1.1 on 2024-09-07 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0003_alter_bookrating_user"),
        ("users", "0002_rename_nickname_profile_username"),
    ]

    operations = [
        migrations.CreateModel(
            name="TakenBook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_returned", models.DateTimeField(auto_created=True, null=True)),
                ("date_taken", models.DateTimeField(auto_created=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("Taken", "Taken"), ("Returned", "Returned")],
                        default="Taken",
                        max_length=20,
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="books.book"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.profile"
                    ),
                ),
            ],
        ),
    ]
