# Generated by Django 5.1.1 on 2024-09-07 18:32

import books.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0004_takenbook"),
        ("users", "0002_rename_nickname_profile_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="takenbook",
            name="deadline_of_return",
            field=models.DateTimeField(default=books.models.default_deadline),
        ),
        migrations.AlterField(
            model_name="takenbook",
            name="date_returned",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="takenbook",
            name="date_taken",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="takenbook",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="taken_books",
                to="users.profile",
            ),
        ),
    ]
